-- =============================================================================
-- RECONSTRUÍDA em 2026-08-24 a partir do estado vivo do banco.
-- =============================================================================
-- Esta versão existia no ledger (`20250803074510`) sem nenhum arquivo local.
-- O SQL original se perdeu — ele foi aplicado direto pelo Dashboard/CLI.
-- O conteúdo abaixo foi extraído do catálogo do PostgreSQL em 2026-08-24 e
-- reproduz os objetos como eles estão hoje. NÃO é o texto original.
--
-- Escrita idempotente de propósito: já está aplicada, e rodar de novo é no-op.
--
-- -----------------------------------------------------------------------------
-- ⚠️  ESTAS SEIS TABELAS SÃO LEGADO MORTO DA ERA "company_id"
-- -----------------------------------------------------------------------------
-- São anteriores à multi-tenancy por `tenant_id`. Nenhuma delas é usada pelo
-- produto hoje. Estão com RLS ligada e ZERO policies — ou seja, negam tudo por
-- padrão. Isso não é descuido: foi a migração
-- `20260513120200_lockdown_legacy_orphan_tables` que as trancou assim.
--
-- Linhas em 2026-08-24: companies=2, evolution_api_instances=1,
-- campaigns=0, company_users=0, jobs=0, reports=0.
--
-- Não confunda com as tabelas vivas de mesmo assunto:
--   campaigns                → a viva é `mass_message_campaigns`
--   evolution_api_instances  → a viva é `whatsapp_instances`
--   jobs                     → a viva é `job_queue`
--   reports                  → as vivas são `report_templates` / `report_data`
--   companies / company_users→ substituídas por `tenants` / `profiles`
--
-- Remover isto é uma decisão do dono do projeto, não desta migração.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.companies (
  id         uuid DEFAULT gen_random_uuid() NOT NULL,
  name       text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.companies DROP CONSTRAINT IF EXISTS companies_pkey CASCADE;
ALTER TABLE public.companies ADD CONSTRAINT companies_pkey PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS public.company_users (
  company_id uuid NOT NULL,
  user_id    uuid NOT NULL,
  role       text DEFAULT 'member'::text
);
DO $$ BEGIN
  ALTER TABLE public.company_users ADD CONSTRAINT company_users_pkey PRIMARY KEY (company_id, user_id);
EXCEPTION WHEN duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.company_users ADD CONSTRAINT company_users_company_id_fkey
    FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.evolution_api_instances (
  id                uuid DEFAULT gen_random_uuid() NOT NULL,
  company_id        uuid NOT NULL,
  instance_name     text NOT NULL,
  server_url        text NOT NULL,
  api_key           text NOT NULL,
  connection_status text DEFAULT 'disconnected'::text,
  qr_code           text,
  last_connected_at timestamp with time zone,
  created_at        timestamp with time zone DEFAULT now()
);
DO $$ BEGIN
  ALTER TABLE public.evolution_api_instances ADD CONSTRAINT evolution_api_instances_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.evolution_api_instances ADD CONSTRAINT evolution_api_instances_instance_name_key UNIQUE (instance_name);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.evolution_api_instances ADD CONSTRAINT evolution_api_instances_company_id_fkey
    FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.campaigns (
  id               uuid DEFAULT gen_random_uuid() NOT NULL,
  company_id       uuid NOT NULL,
  name             text NOT NULL,
  message_template text NOT NULL,
  status           text DEFAULT 'draft'::text,
  created_at       timestamp with time zone DEFAULT now()
);
DO $$ BEGIN
  ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_company_id_fkey
    FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.jobs (
  id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  company_id       uuid NOT NULL,
  type             text NOT NULL,
  payload          jsonb,
  status           text DEFAULT 'pending'::text,
  run_at           timestamp with time zone DEFAULT now(),
  completed_at     timestamp with time zone,
  current_attempts integer DEFAULT 0,
  max_attempts     integer DEFAULT 3,
  error_message    text,
  created_at       timestamp with time zone DEFAULT now()
);
DO $$ BEGIN
  ALTER TABLE public.jobs ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.jobs ADD CONSTRAINT jobs_company_id_fkey
    FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.reports (
  id          uuid DEFAULT gen_random_uuid() NOT NULL,
  company_id  uuid NOT NULL,
  name        text NOT NULL,
  description text,
  query       text NOT NULL,
  created_by  uuid,
  created_at  timestamp with time zone DEFAULT now(),
  updated_at  timestamp with time zone DEFAULT now()
);
DO $$ BEGIN
  ALTER TABLE public.reports ADD CONSTRAINT reports_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.reports ADD CONSTRAINT reports_company_id_fkey
    FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trancadas: RLS ligada, nenhuma policy. Nega tudo, inclusive para authenticated.
-- (Estado real conferido em 2026-08-24 — mantido aqui para o rebuild reproduzir.)
ALTER TABLE public.companies               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evolution_api_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports                 ENABLE ROW LEVEL SECURITY;
